Update covid data downloading
covid19cz/erouska-backend pull request #72
Opened 2020-09-10 19:38 UTC by dizider

2020-09-10 20:33 UTC, jendakol approved these changes

2020-09-11 07:50 UTC, marekaf commented
this should be deleted too https://github.com/covid19cz/erouska-backend/blob/develop/builders/deploy.yaml#L79

2020-09-11 07:52 UTC, marekaf approved these changes
otherwise it is looking good, but I'm thinking that we don't really need two firestore collections anymore, one would be enough, it would simplify downloading & storing and then getting the data.

2020-09-11 14:08 UTC, jendakol requested changes

2020-09-11 14:08 UTC, jendakol commented on builders/deploy.yaml
>    args:
The whole block needs to be removed, not just the name :-)

2020-09-12 07:44 UTC, jendakol approved these changes

2020-09-12 07:45 UTC, merged